### ISSUE TITLE
🏁 Agent-as-a-Service 全链路交付任务启动

### ISSUE THREAD

**Issue by dinfeng777** [dinfeng777/demo#1]
## 🏁 任务背景

我们决定抛弃传统“自己造轮子”流程，直接对接 **2025-05 Agent-as-a-Service 生态**，在 3 周内把「个人 + AI」升级为 **小型 AI-原生工作室**。

---

## 🎯 目标（T + 3 周）

1. **W0–W1：环境即服务**
   - LangGraph Cloud & Flowise 搭好基础编排
   - GitHub Copilot Coding Agent 启用
   - Azure Foundry 模型热切换可用
2. **W1–W2：Meta-Agent MVP**
   - Flowise 拖拽 Crawler → Synthesizer → Architect 节点
   - Copilot 自动生成骨架仓库 + 单测
   - RAG-as-API 返回《模块拆解 + 技栈矩阵》Markdown
3. **W2–W3：DevOps 自动闭环**
   - 引入 Spacelift Pipeline；CI 触发 Copilot 自修
   - CodeGuru 静态分析 → AutoGen Refactor-Agent 处理
   - LangGraph 状态持久化；失败任务自动重试
4. 整链路：Issue → 代码 → CI/CD → Docker 镜像 ≤ 30 min

---

## 🔖 Label 规范

| Label                | 作用                 |
| -------------------- | ------------------ |
| `assign-to-copilot`  | 代码与测试全自动交给 Copilot |
| `backlog/tech-debt`  | 技术债批量队列，低优先        |
| `needs-human-review` | 关键 PR 需人工复审        |

---

## 📝 Issue 模板建议

请将下方 YAML 模板内容同步到 `.github/ISSUE_TEMPLATE/agent_task.yml`

```yaml
name: "🤖 Agent 任务"
labels: ["assign-to-copilot"]
body:
  - type: textarea
    id: task
    attributes:
      label: 任务描述
      placeholder: 例：为 LangGraph Demo 添加 OAuth 登录；覆盖率≥85%…
    validations: { required: true }
  - type: input
    id: success
    attributes:
      label: 完成判据
      placeholder: 测试全绿 + PR 无冲突 + 性能不下降
    validations: { required: true }
```

---

## 🚀 首批三条 Issue（建议直接贴到仓库）

| # | Title                         | 主要内容                                                                  | Label             |
| - | ----------------------------- | ------------------------------------------------------------------------- | ----------------- |
| 1 | `feat/langgraph-dag-skeleton` | 使用 Flowise 创建 3 节点 DAG：Crawler→Synthesizer→Architect；自动生成 README & 单测 | assign-to-copilot |
| 2 | `ci/spacelift-template`       | 引入 Spacelift 基础流水线，包含 lint+unit+docker build                          | assign-to-copilot |
| 3 | `backlog/upgrade-deps`        | 升级全部 NPM 依赖到最新 minor；修复因升级导致的测试失败                                     | backlog/tech-debt |

---

## 🛠 技术栈与账户

- **Orchestration**：LangGraph Cloud (托管) + Flowise UI
- **LLM 热切换**：GPT-4o / Claude-3 / Grok 3 via Azure Foundry
- **编码执行**：GitHub Copilot Coding Agent + AutoGen v2 “Executor”
- **Knowledge / RAG**：Weaviate Cloud + Azure Cognitive Search
- **DevOps**：Spacelift + AWS CodeGuru + Atlassian Intelligence
- **界面**：Telegram Bot & VS Code 插件（Flowise 自动生成）

---

## ⏱ 时间线（UTC+8）

| 日期           | 里程碑 & 检查点                               |
| ------------ | --------------------------------------- |
| **5-23（明天）** | 功能开关全部就绪；Issue 模板合并到主分支                 |
| 5-25         | Copilot PR #1 合并；Spacelift CI 通过        |
| 5-30         | Meta-Agent MVP 在 LangGraph 运行成功，输出技术栈矩阵 |
| 6-06         | 自动闭环：Issue→Docker 镜像 30 min 内完成         |

---

## ✅ 验收标准

1. **PR 自动创建 & 流水线全绿**
2. 模块拆解文档含：任务树 / 技栈矩阵 / 依赖图
3. Docker 镜像可本地 `docker run` 成功启动

---

> **说明给团队 / Copilot**
>
> - 所有带 `assign-to-copilot` 的 Issue 由 Copilot Coding Agent 全权处理。
> - 如果 PR 失败 2 次，自行标记 `needs-human-review`，由人工介入。
> - 所有步骤日志自动同步到 Telegram Bot，方便移动审阅。

---

复制以上内容 → 新建一条顶级 Issue，即可触发全链路。
**接下来只需提供你的第一个真实业务需求一句话**（如“做一个简单订餐小程序”），我会在 W0–W1 阶段替你生成 DAG 并让 Copilot 出骨架 PR。
